language: node_js
sudo: false
node_js:
  - 8
env:
  - DIST_DIR=eleme-demo
  - DIST_DIR=with-redux
  - DIST_DIR=with-dva
matrix:
  fast_finish: true
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1366x768x24 > /dev/null 2>&1 &
script:
  - cd $DIST_DIR
  - npm i
  - npm run ci
after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
